export interface WasteAuthority {
  name: string
  fullName: string
  code: string
  website?: string
  phone?: string
  email?: string
  headquarters: string
  binIdFormat: string
  billCycle: "monthly" | "quarterly" | "annually"
  averageBill: number
  paymentMethods: string[]
  zones: string[]
}

export interface StateData {
  name: string
  code: string
  capital: string
  wasteAuthority: WasteAuthority
  lgas: string[]
  population: number
  isActive: boolean
}

export const NIGERIAN_STATES: Record<string, StateData> = {
  lagos: {
    name: "Lagos",
    code: "LA",
    capital: "Ikeja",
    wasteAuthority: {
      name: "LAWMA",
      fullName: "Lagos Waste Management Authority",
      code: "LAWMA",
      website: "https://lawma.gov.ng",
      phone: "+234 1 234 5678",
      email: "info@lawma.gov.ng",
      headquarters: "Ikeja",
      binIdFormat: "LA######",
      billCycle: "monthly",
      averageBill: 7500,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money", "pos"],
      zones: ["Lagos Island", "Lagos Mainland", "Surulere", "Ikeja", "Ikorodu"],
    },
    lgas: [
      "Agege",
      "Ajeromi-Ifelodun",
      "Alimosho",
      "Amuwo-Odofin",
      "Apapa",
      "Badagry",
      "Epe",
      "Eti Osa",
      "Ibeju-Lekki",
      "Ifako-Ijaiye",
      "Ikeja",
      "Ikorodu",
      "Kosofe",
      "Lagos Island",
      "Lagos Mainland",
      "Mushin",
      "Ojo",
      "Oshodi-Isolo",
      "Shomolu",
      "Surulere",
    ],
    population: 9113605,
    isActive: true,
  },
  fct: {
    name: "Federal Capital Territory",
    code: "FC",
    capital: "Abuja",
    wasteAuthority: {
      name: "AEPB",
      fullName: "Abuja Environmental Protection Board",
      code: "AEPB",
      website: "https://aepb.gov.ng",
      phone: "+234 9 234 5678",
      email: "info@aepb.gov.ng",
      headquarters: "Abuja",
      binIdFormat: "FC######",
      billCycle: "monthly",
      averageBill: 6500,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Abuja Municipal", "Gwagwalada", "Kuje", "Bwari", "Kwali", "Abaji"],
    },
    lgas: ["Abaji", "Bwari", "Gwagwalada", "Kuje", "Municipal Area Council", "Kwali"],
    population: 1406239,
    isActive: true,
  },
  enugu: {
    name: "Enugu",
    code: "EN",
    capital: "Enugu",
    wasteAuthority: {
      name: "ESWAMA",
      fullName: "Enugu State Waste Management Authority",
      code: "ESWAMA",
      website: "https://enugustate.gov.ng",
      phone: "+234 829 456 7890",
      email: "info@eswama.gov.ng",
      headquarters: "Enugu",
      binIdFormat: "EN######",
      billCycle: "monthly",
      averageBill: 4000,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Enugu", "Nsukka", "Oji River", "Awgu", "Udi"],
    },
    lgas: [
      "Aninri",
      "Awgu",
      "Enugu East",
      "Enugu North",
      "Enugu South",
      "Ezeagu",
      "Igbo Etiti",
      "Igbo Eze North",
      "Igbo Eze South",
      "Isi Uzo",
      "Nkanu East",
      "Nkanu West",
      "Nsukka",
      "Oji River",
      "Udenu",
      "Udi",
      "Uzo Uwani",
    ],
    population: 3267837,
    isActive: true,
  },
  abia: {
    name: "Abia",
    code: "AB",
    capital: "Umuahia",
    wasteAuthority: {
      name: "ASEPA",
      fullName: "Abia State Environmental Protection Agency",
      code: "ASEPA",
      website: "https://abiastate.gov.ng",
      phone: "+234 803 123 4567",
      email: "info@asepa.gov.ng",
      headquarters: "Umuahia",
      binIdFormat: "AB######",
      billCycle: "monthly",
      averageBill: 3500,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Umuahia North", "Umuahia South", "Aba North", "Aba South", "Arochukwu"],
    },
    lgas: [
      "Aba North",
      "Aba South",
      "Arochukwu",
      "Bende",
      "Ikwuano",
      "Isiala Ngwa North",
      "Isiala Ngwa South",
      "Isuikwuato",
      "Obi Ngwa",
      "Ohafia",
      "Osisioma",
      "Ugwunagbo",
      "Ukwa East",
      "Ukwa West",
      "Umuahia North",
      "Umuahia South",
      "Umu Nneochi",
    ],
    population: 2833999,
    isActive: true,
  },
  adamawa: {
    name: "Adamawa",
    code: "AD",
    capital: "Yola",
    wasteAuthority: {
      name: "ADSEMA",
      fullName: "Adamawa State Environmental Management Agency",
      code: "ADSEMA",
      website: "https://adamawastate.gov.ng",
      phone: "+234 805 234 5678",
      email: "info@adsema.gov.ng",
      headquarters: "Yola",
      binIdFormat: "AD######",
      billCycle: "quarterly",
      averageBill: 4200,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Yola North", "Yola South", "Jimeta", "Mubi North", "Mubi South"],
    },
    lgas: [
      "Demsa",
      "Fufure",
      "Ganye",
      "Gayuk",
      "Gombi",
      "Grie",
      "Hong",
      "Jada",
      "Lamurde",
      "Madagali",
      "Maiha",
      "Mayo Belwa",
      "Michika",
      "Mubi North",
      "Mubi South",
      "Numan",
      "Shelleng",
      "Song",
      "Toungo",
      "Yola North",
      "Yola South",
    ],
    population: 3178950,
    isActive: true,
  },
  akwaibom: {
    name: "Akwa Ibom",
    code: "AK",
    capital: "Uyo",
    wasteAuthority: {
      name: "AKSEMA",
      fullName: "Akwa Ibom State Environmental Management Agency",
      code: "AKSEMA",
      website: "https://akwaibomstate.gov.ng",
      phone: "+234 807 345 6789",
      email: "info@aksema.gov.ng",
      headquarters: "Uyo",
      binIdFormat: "AK######",
      billCycle: "monthly",
      averageBill: 4500,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Uyo", "Ikot Ekpene", "Eket", "Abak", "Oron"],
    },
    lgas: [
      "Abak",
      "Eastern Obolo",
      "Eket",
      "Esit Eket",
      "Essien Udim",
      "Etim Ekpo",
      "Etinan",
      "Ibeno",
      "Ibesikpo Asutan",
      "Ibiono-Ibom",
      "Ika",
      "Ikono",
      "Ikot Abasi",
      "Ikot Ekpene",
      "Ini",
      "Itu",
      "Mbo",
      "Mkpat-Enin",
      "Nsit-Atai",
      "Nsit-Ibom",
      "Nsit-Ubium",
      "Obot Akara",
      "Okobo",
      "Onna",
      "Oron",
      "Oruk Anam",
      "Udung-Uko",
      "Ukanafun",
      "Uruan",
      "Urue-Offong/Oruko",
      "Uyo",
    ],
    population: 3902051,
    isActive: true,
  },
  anambra: {
    name: "Anambra",
    code: "AN",
    capital: "Awka",
    wasteAuthority: {
      name: "ANSEMA",
      fullName: "Anambra State Environmental Management Agency",
      code: "ANSEMA",
      website: "https://anambrastate.gov.ng",
      phone: "+234 809 456 7890",
      email: "info@ansema.gov.ng",
      headquarters: "Awka",
      binIdFormat: "AN######",
      billCycle: "monthly",
      averageBill: 3800,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Ihiala"],
    },
    lgas: [
      "Aguata",
      "Anambra East",
      "Anambra West",
      "Anaocha",
      "Awka North",
      "Awka South",
      "Ayamelum",
      "Dunukofia",
      "Ekwusigo",
      "Idemili North",
      "Idemili South",
      "Ihiala",
      "Njikoka",
      "Nnewi North",
      "Nnewi South",
      "Ogbaru",
      "Onitsha North",
      "Onitsha South",
      "Orumba North",
      "Orumba South",
      "Oyi",
    ],
    population: 4177828,
    isActive: true,
  },
  bauchi: {
    name: "Bauchi",
    code: "BA",
    capital: "Bauchi",
    wasteAuthority: {
      name: "BASEPA",
      fullName: "Bauchi State Environmental Protection Agency",
      code: "BASEPA",
      website: "https://bauchistate.gov.ng",
      phone: "+234 811 567 8901",
      email: "info@basepa.gov.ng",
      headquarters: "Bauchi",
      binIdFormat: "BA######",
      billCycle: "quarterly",
      averageBill: 3200,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Bauchi", "Azare", "Misau", "Jama'are", "Dass"],
    },
    lgas: [
      "Alkaleri",
      "Bauchi",
      "Bogoro",
      "Damban",
      "Darazo",
      "Dass",
      "Gamawa",
      "Ganjuwa",
      "Giade",
      "Itas/Gadau",
      "Jama'are",
      "Katagum",
      "Kirfi",
      "Misau",
      "Ningi",
      "Shira",
      "Tafawa Balewa",
      "Toro",
      "Warji",
      "Zaki",
    ],
    population: 4676465,
    isActive: true,
  },
  bayelsa: {
    name: "Bayelsa",
    code: "BY",
    capital: "Yenagoa",
    wasteAuthority: {
      name: "BYSEMA",
      fullName: "Bayelsa State Environmental Management Agency",
      code: "BYSEMA",
      website: "https://bayelsastate.gov.ng",
      phone: "+234 813 678 9012",
      email: "info@bysema.gov.ng",
      headquarters: "Yenagoa",
      binIdFormat: "BY######",
      billCycle: "monthly",
      averageBill: 4800,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Yenagoa", "Brass", "Sagbama", "Kolokuma/Opokuma", "Ogbia"],
    },
    lgas: ["Brass", "Ekeremor", "Kolokuma/Opokuma", "Nembe", "Ogbia", "Sagbama", "Southern Ijaw", "Yenagoa"],
    population: 1704515,
    isActive: true,
  },
  benue: {
    name: "Benue",
    code: "BE",
    capital: "Makurdi",
    wasteAuthority: {
      name: "BESEMA",
      fullName: "Benue State Environmental Management Agency",
      code: "BESEMA",
      website: "https://benuestate.gov.ng",
      phone: "+234 815 789 0123",
      email: "info@besema.gov.ng",
      headquarters: "Makurdi",
      binIdFormat: "BE######",
      billCycle: "quarterly",
      averageBill: 3600,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala", "Vandeikya"],
    },
    lgas: [
      "Ado",
      "Agatu",
      "Apa",
      "Buruku",
      "Gboko",
      "Guma",
      "Gwer East",
      "Gwer West",
      "Katsina-Ala",
      "Konshisha",
      "Kwande",
      "Logo",
      "Makurdi",
      "Obi",
      "Ogbadibo",
      "Ohimini",
      "Oju",
      "Okpokwu",
      "Otukpo",
      "Tarka",
      "Ukum",
      "Ushongo",
      "Vandeikya",
    ],
    population: 4253641,
    isActive: true,
  },
  borno: {
    name: "Borno",
    code: "BO",
    capital: "Maiduguri",
    wasteAuthority: {
      name: "BOSEMA",
      fullName: "Borno State Environmental Management Agency",
      code: "BOSEMA",
      website: "https://bornostate.gov.ng",
      phone: "+234 817 890 1234",
      email: "info@bosema.gov.ng",
      headquarters: "Maiduguri",
      binIdFormat: "BO######",
      billCycle: "quarterly",
      averageBill: 2800,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Maiduguri", "Biu", "Bama", "Dikwa", "Gubio"],
    },
    lgas: [
      "Abadam",
      "Askira/Uba",
      "Bama",
      "Bayo",
      "Biu",
      "Chibok",
      "Damboa",
      "Dikwa",
      "Gubio",
      "Guzamala",
      "Gwoza",
      "Hawul",
      "Jere",
      "Kaga",
      "Kala/Balge",
      "Konduga",
      "Kukawa",
      "Kwaya Kusar",
      "Mafa",
      "Magumeri",
      "Maiduguri",
      "Marte",
      "Mobbar",
      "Monguno",
      "Ngala",
      "Nganzai",
      "Shani",
    ],
    population: 4171104,
    isActive: false, // Due to security challenges
  },
  crossriver: {
    name: "Cross River",
    code: "CR",
    capital: "Calabar",
    wasteAuthority: {
      name: "CRSEMA",
      fullName: "Cross River State Environmental Management Agency",
      code: "CRSEMA",
      website: "https://crossriverstate.gov.ng",
      phone: "+234 819 901 2345",
      email: "info@crsema.gov.ng",
      headquarters: "Calabar",
      binIdFormat: "CR######",
      billCycle: "monthly",
      averageBill: 4200,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Calabar Municipal", "Calabar South", "Ogoja", "Ikom", "Obudu"],
    },
    lgas: [
      "Abi",
      "Akamkpa",
      "Akpabuyo",
      "Bakassi",
      "Bekwarra",
      "Biase",
      "Boki",
      "Calabar Municipal",
      "Calabar South",
      "Etung",
      "Ikom",
      "Obanliku",
      "Obubra",
      "Obudu",
      "Odukpani",
      "Ogoja",
      "Yakoko",
      "Yala",
    ],
    population: 2892988,
    isActive: true,
  },
  delta: {
    name: "Delta",
    code: "DT",
    capital: "Asaba",
    wasteAuthority: {
      name: "DESEMA",
      fullName: "Delta State Environmental Management Agency",
      code: "DESEMA",
      website: "https://deltastate.gov.ng",
      phone: "+234 821 012 3456",
      email: "info@desema.gov.ng",
      headquarters: "Asaba",
      binIdFormat: "DT######",
      billCycle: "monthly",
      averageBill: 4600,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor"],
    },
    lgas: [
      "Aniocha North",
      "Aniocha South",
      "Bomadi",
      "Burutu",
      "Ethiope East",
      "Ethiope West",
      "Ika North East",
      "Ika South",
      "Isoko North",
      "Isoko South",
      "Ndokwa East",
      "Ndokwa West",
      "Okpe",
      "Oshimili North",
      "Oshimili South",
      "Patani",
      "Sapele",
      "Udu",
      "Ughelli North",
      "Ughelli South",
      "Ukwuani",
      "Uvwie",
      "Warri North",
      "Warri South",
      "Warri South West",
    ],
    population: 4112445,
    isActive: true,
  },
  ebonyi: {
    name: "Ebonyi",
    code: "EB",
    capital: "Abakaliki",
    wasteAuthority: {
      name: "EBSEMA",
      fullName: "Ebonyi State Environmental Management Agency",
      code: "EBSEMA",
      website: "https://ebonyistate.gov.ng",
      phone: "+234 823 123 4567",
      email: "info@ebsema.gov.ng",
      headquarters: "Abakaliki",
      binIdFormat: "EB######",
      billCycle: "quarterly",
      averageBill: 3400,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Abakaliki", "Afikpo", "Onueke", "Ezza", "Ikwo"],
    },
    lgas: [
      "Abakaliki",
      "Afikpo North",
      "Afikpo South",
      "Ebonyi",
      "Ezza North",
      "Ezza South",
      "Ikwo",
      "Ishielu",
      "Ivo",
      "Izzi",
      "Ohaozara",
      "Ohaukwu",
      "Onicha",
    ],
    population: 2176947,
    isActive: true,
  },
  edo: {
    name: "Edo",
    code: "ED",
    capital: "Benin City",
    wasteAuthority: {
      name: "EDSEMA",
      fullName: "Edo State Environmental Management Agency",
      code: "EDSEMA",
      website: "https://edostate.gov.ng",
      phone: "+234 825 234 5678",
      email: "info@edsema.gov.ng",
      headquarters: "Benin City",
      binIdFormat: "ED######",
      billCycle: "monthly",
      averageBill: 4400,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Benin City", "Auchi", "Ekpoma", "Uromi", "Igarra"],
    },
    lgas: [
      "Akoko-Edo",
      "Egor",
      "Esan Central",
      "Esan North-East",
      "Esan South-East",
      "Esan West",
      "Etsako Central",
      "Etsako East",
      "Etsako West",
      "Igueben",
      "Ikpoba Okha",
      "Oredo",
      "Orhionmwon",
      "Ovia North-East",
      "Ovia South-West",
      "Owan East",
      "Owan West",
      "Uhunmwonde",
    ],
    population: 3233366,
    isActive: true,
  },
  ekiti: {
    name: "Ekiti",
    code: "EK",
    capital: "Ado-Ekiti",
    wasteAuthority: {
      name: "EKSEMA",
      fullName: "Ekiti State Environmental Management Agency",
      code: "EKSEMA",
      website: "https://ekitistate.gov.ng",
      phone: "+234 827 345 6789",
      email: "info@eksema.gov.ng",
      headquarters: "Ado-Ekiti",
      binIdFormat: "EK######",
      billCycle: "quarterly",
      averageBill: 3300,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Ado-Ekiti", "Ikere", "Aramoko", "Ijero", "Ise-Orun"],
    },
    lgas: [
      "Ado Ekiti",
      "Efon",
      "Ekiti East",
      "Ekiti South-West",
      "Ekiti West",
      "Emure",
      "Gbonyin",
      "Ido Osi",
      "Ijero",
      "Ikere",
      "Ikole",
      "Ilejemeje",
      "Irepodun/Ifelodun",
      "Ise/Orun",
      "Moba",
      "Oye",
    ],
    population: 2384212,
    isActive: true,
  },
  gombe: {
    name: "Gombe",
    code: "GO",
    capital: "Gombe",
    wasteAuthority: {
      name: "GOSEMA",
      fullName: "Gombe State Environmental Management Agency",
      code: "GOSEMA",
      website: "https://gombestate.gov.ng",
      phone: "+234 831 567 8901",
      email: "info@gosema.gov.ng",
      headquarters: "Gombe",
      binIdFormat: "GO######",
      billCycle: "quarterly",
      averageBill: 3100,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Gombe", "Billiri", "Kaltungo", "Dukku", "Nafada"],
    },
    lgas: [
      "Akko",
      "Balanga",
      "Billiri",
      "Dukku",
      "Funakaye",
      "Gombe",
      "Kaltungo",
      "Kwami",
      "Nafada",
      "Shongom",
      "Yamaltu/Deba",
    ],
    population: 2365040,
    isActive: true,
  },
  imo: {
    name: "Imo",
    code: "IM",
    capital: "Owerri",
    wasteAuthority: {
      name: "IMSEMA",
      fullName: "Imo State Environmental Management Agency",
      code: "IMSEMA",
      website: "https://imostate.gov.ng",
      phone: "+234 833 678 9012",
      email: "info@imsema.gov.ng",
      headquarters: "Owerri",
      binIdFormat: "IM######",
      billCycle: "monthly",
      averageBill: 3900,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Owerri", "Orlu", "Okigwe", "Mbaise", "Oguta"],
    },
    lgas: [
      "Aboh Mbaise",
      "Ahiazu Mbaise",
      "Ehime Mbano",
      "Ezinihitte",
      "Ideato North",
      "Ideato South",
      "Ihitte/Uboma",
      "Ikeduru",
      "Isiala Mbano",
      "Isu",
      "Mbaitoli",
      "Ngor Okpala",
      "Njaba",
      "Nkwerre",
      "Nwangele",
      "Obowo",
      "Oguta",
      "Ohaji/Egbema",
      "Okigwe",
      "Orlu",
      "Orsu",
      "Oru East",
      "Oru West",
      "Owerri Municipal",
      "Owerri North",
      "Owerri West",
      "Unuimo",
    ],
    population: 3927563,
    isActive: true,
  },
  jigawa: {
    name: "Jigawa",
    code: "JI",
    capital: "Dutse",
    wasteAuthority: {
      name: "JISEMA",
      fullName: "Jigawa State Environmental Management Agency",
      code: "JISEMA",
      website: "https://jigawastate.gov.ng",
      phone: "+234 835 789 0123",
      email: "info@jisema.gov.ng",
      headquarters: "Dutse",
      binIdFormat: "JI######",
      billCycle: "quarterly",
      averageBill: 2900,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Dutse", "Hadejia", "Gumel", "Kazaure", "Ringim"],
    },
    lgas: [
      "Auyo",
      "Babura",
      "Biriniwa",
      "Birnin Kudu",
      "Buji",
      "Dutse",
      "Gagarawa",
      "Garki",
      "Gumel",
      "Guri",
      "Gwaram",
      "Gwiwa",
      "Hadejia",
      "Jahun",
      "Kafin Hausa",
      "Kazaure",
      "Kiri Kasama",
      "Kiyawa",
      "Kaugama",
      "Maigatari",
      "Malam Madori",
      "Miga",
      "Ringim",
      "Roni",
      "Sule Tankarkar",
      "Taura",
      "Yankwashi",
    ],
    population: 4361002,
    isActive: true,
  },
  kaduna: {
    name: "Kaduna",
    code: "KD",
    capital: "Kaduna",
    wasteAuthority: {
      name: "KASEMA",
      fullName: "Kaduna State Environmental Management Agency",
      code: "KASEMA",
      website: "https://kadunastate.gov.ng",
      phone: "+234 837 890 1234",
      email: "info@kasema.gov.ng",
      headquarters: "Kaduna",
      binIdFormat: "KD######",
      billCycle: "monthly",
      averageBill: 4100,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Kaduna North", "Kaduna South", "Zaria", "Kafanchan", "Soba"],
    },
    lgas: [
      "Birnin Gwari",
      "Chikun",
      "Giwa",
      "Igabi",
      "Ikara",
      "Jaba",
      "Jema'a",
      "Kachia",
      "Kaduna North",
      "Kaduna South",
      "Kagarko",
      "Kajuru",
      "Kaura",
      "Kauru",
      "Kubau",
      "Kudan",
      "Lere",
      "Makarfi",
      "Sabon Gari",
      "Sanga",
      "Soba",
      "Zangon Kataf",
      "Zaria",
    ],
    population: 6113503,
    isActive: true,
  },
  kano: {
    name: "Kano",
    code: "KN",
    capital: "Kano",
    wasteAuthority: {
      name: "KANSEMA",
      fullName: "Kano State Environmental Management Agency",
      code: "KANSEMA",
      website: "https://kanostate.gov.ng",
      phone: "+234 839 901 2345",
      email: "info@kansema.gov.ng",
      headquarters: "Kano",
      binIdFormat: "KN######",
      billCycle: "monthly",
      averageBill: 3700,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Kano Municipal", "Fagge", "Dala", "Gwale", "Tarauni"],
    },
    lgas: [
      "Ajingi",
      "Albasu",
      "Bagwai",
      "Bebeji",
      "Bichi",
      "Bunkure",
      "Dala",
      "Dambatta",
      "Dawakin Kudu",
      "Dawakin Tofa",
      "Doguwa",
      "Fagge",
      "Gabasawa",
      "Garko",
      "Garun Mallam",
      "Gaya",
      "Gezawa",
      "Gwale",
      "Gwarzo",
      "Kabo",
      "Kano Municipal",
      "Karaye",
      "Kibiya",
      "Kiru",
      "Kumbotso",
      "Kunchi",
      "Kura",
      "Madobi",
      "Makoda",
      "Minjibir",
      "Nasarawa",
      "Rano",
      "Rimin Gado",
      "Rogo",
      "Shanono",
      "Sumaila",
      "Takai",
      "Tarauni",
      "Tofa",
      "Tsanyawa",
      "Tudun Wada",
      "Ungogo",
      "Warawa",
      "Wudil",
    ],
    population: 9401288,
    isActive: true,
  },
  katsina: {
    name: "Katsina",
    code: "KT",
    capital: "Katsina",
    wasteAuthority: {
      name: "KATSEMA",
      fullName: "Katsina State Environmental Management Agency",
      code: "KATSEMA",
      website: "https://katsinastate.gov.ng",
      phone: "+234 841 012 3456",
      email: "info@katsema.gov.ng",
      headquarters: "Katsina",
      binIdFormat: "KT######",
      billCycle: "quarterly",
      averageBill: 3000,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Katsina", "Funtua", "Daura", "Malumfashi", "Dutsin-Ma"],
    },
    lgas: [
      "Bakori",
      "Batagarawa",
      "Batsari",
      "Baure",
      "Bindawa",
      "Charanchi",
      "Dandume",
      "Danja",
      "Dan Musa",
      "Daura",
      "Dutsi",
      "Dutsin Ma",
      "Faskari",
      "Funtua",
      "Ingawa",
      "Jibia",
      "Kafur",
      "Kaita",
      "Kankara",
      "Kankia",
      "Katsina",
      "Kurfi",
      "Kusada",
      "Mai'Adua",
      "Malumfashi",
      "Mani",
      "Mashi",
      "Matazu",
      "Musawa",
      "Rimi",
      "Sabuwa",
      "Safana",
      "Sandamu",
      "Zango",
    ],
    population: 5801584,
    isActive: true,
  },
  kebbi: {
    name: "Kebbi",
    code: "KB",
    capital: "Birnin Kebbi",
    wasteAuthority: {
      name: "KEBSEMA",
      fullName: "Kebbi State Environmental Management Agency",
      code: "KEBSEMA",
      website: "https://kebbistate.gov.ng",
      phone: "+234 843 123 4567",
      email: "info@kebsema.gov.ng",
      headquarters: "Birnin Kebbi",
      binIdFormat: "KB######",
      billCycle: "quarterly",
      averageBill: 2700,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Birnin Kebbi", "Argungu", "Yauri", "Zuru", "Bagudo"],
    },
    lgas: [
      "Aleiro",
      "Arewa Dandi",
      "Argungu",
      "Augie",
      "Bagudo",
      "Birnin Kebbi",
      "Bunza",
      "Dandi",
      "Fakai",
      "Gwandu",
      "Jega",
      "Kalgo",
      "Koko/Besse",
      "Maiyama",
      "Ngaski",
      "Sakaba",
      "Shanga",
      "Suru",
      "Wasagu/Danko",
      "Yauri",
      "Zuru",
    ],
    population: 3256541,
    isActive: true,
  },
  kogi: {
    name: "Kogi",
    code: "KG",
    capital: "Lokoja",
    wasteAuthority: {
      name: "KOSEMA",
      fullName: "Kogi State Environmental Management Agency",
      code: "KOSEMA",
      website: "https://kogistate.gov.ng",
      phone: "+234 845 234 5678",
      email: "info@kosema.gov.ng",
      headquarters: "Lokoja",
      binIdFormat: "KG######",
      billCycle: "monthly",
      averageBill: 3800,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Lokoja", "Okene", "Kabba", "Ankpa", "Idah"],
    },
    lgas: [
      "Adavi",
      "Ajaokuta",
      "Ankpa",
      "Bassa",
      "Dekina",
      "Ibaji",
      "Idah",
      "Igalamela Odolu",
      "Ijumu",
      "Kabba/Bunu",
      "Kogi",
      "Lokoja",
      "Mopa Muro",
      "Ofu",
      "Ogori/Magongo",
      "Okehi",
      "Okene",
      "Olamaboro",
      "Omala",
      "Yagba East",
      "Yagba West",
    ],
    population: 3314043,
    isActive: true,
  },
  kwara: {
    name: "Kwara",
    code: "KW",
    capital: "Ilorin",
    wasteAuthority: {
      name: "KWSEMA",
      fullName: "Kwara State Environmental Management Agency",
      code: "KWSEMA",
      website: "https://kwarastate.gov.ng",
      phone: "+234 847 345 6789",
      email: "info@kwsema.gov.ng",
      headquarters: "Ilorin",
      binIdFormat: "KW######",
      billCycle: "monthly",
      averageBill: 3600,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Ilorin West", "Ilorin East", "Ilorin South", "Offa", "Omu-Aran"],
    },
    lgas: [
      "Asa",
      "Baruten",
      "Edu",
      "Ekiti",
      "Ifelodun",
      "Ilorin East",
      "Ilorin South",
      "Ilorin West",
      "Irepodun",
      "Isin",
      "Kaiama",
      "Moro",
      "Offa",
      "Oke Ero",
      "Oyun",
      "Pategi",
    ],
    population: 2371089,
    isActive: true,
  },
  nasarawa: {
    name: "Nasarawa",
    code: "NA",
    capital: "Lafia",
    wasteAuthority: {
      name: "NASEMA",
      fullName: "Nasarawa State Environmental Management Agency",
      code: "NASEMA",
      website: "https://nasarawastate.gov.ng",
      phone: "+234 849 456 7890",
      email: "info@nasema.gov.ng",
      headquarters: "Lafia",
      binIdFormat: "NA######",
      billCycle: "quarterly",
      averageBill: 3300,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Lafia", "Keffi", "Akwanga", "Nasarawa", "Doma"],
    },
    lgas: [
      "Akwanga",
      "Awe",
      "Doma",
      "Karu",
      "Keana",
      "Keffi",
      "Kokona",
      "Lafia",
      "Nasarawa",
      "Nasarawa Egon",
      "Obi",
      "Toto",
      "Wamba",
    ],
    population: 1869377,
    isActive: true,
  },
  niger: {
    name: "Niger",
    code: "NI",
    capital: "Minna",
    wasteAuthority: {
      name: "NISEMA",
      fullName: "Niger State Environmental Management Agency",
      code: "NISEMA",
      website: "https://nigerstate.gov.ng",
      phone: "+234 851 567 8901",
      email: "info@nisema.gov.ng",
      headquarters: "Minna",
      binIdFormat: "NI######",
      billCycle: "quarterly",
      averageBill: 3200,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Minna", "Bida", "Kontagora", "Suleja", "New Bussa"],
    },
    lgas: [
      "Agaie",
      "Agwara",
      "Bida",
      "Borgu",
      "Bosso",
      "Chanchaga",
      "Edati",
      "Gbako",
      "Gurara",
      "Katcha",
      "Kontagora",
      "Lapai",
      "Lavun",
      "Magama",
      "Mariga",
      "Mashegu",
      "Mokwa",
      "Moya",
      "Paikoro",
      "Rafi",
      "Rijau",
      "Shiroro",
      "Suleja",
      "Tafa",
      "Wushishi",
    ],
    population: 3954772,
    isActive: true,
  },
  ogun: {
    name: "Ogun",
    code: "OG",
    capital: "Abeokuta",
    wasteAuthority: {
      name: "OGSEMA",
      fullName: "Ogun State Environmental Management Agency",
      code: "OGSEMA",
      website: "https://ogunstate.gov.ng",
      phone: "+234 853 678 9012",
      email: "info@ogsema.gov.ng",
      headquarters: "Abeokuta",
      binIdFormat: "OG######",
      billCycle: "monthly",
      averageBill: 4300,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Abeokuta North", "Abeokuta South", "Sagamu", "Ijebu Ode", "Ota"],
    },
    lgas: [
      "Abeokuta North",
      "Abeokuta South",
      "Ado-Odo/Ota",
      "Egbado North",
      "Egbado South",
      "Ewekoro",
      "Ifo",
      "Ijebu East",
      "Ijebu North",
      "Ijebu North East",
      "Ijebu Ode",
      "Ikenne",
      "Imeko Afon",
      "Ipokia",
      "Obafemi Owode",
      "Odeda",
      "Odogbolu",
      "Ogun Waterside",
      "Remo North",
      "Shagamu",
    ],
    population: 3751140,
    isActive: true,
  },
  ondo: {
    name: "Ondo",
    code: "ON",
    capital: "Akure",
    wasteAuthority: {
      name: "ONSEMA",
      fullName: "Ondo State Environmental Management Agency",
      code: "ONSEMA",
      website: "https://ondostate.gov.ng",
      phone: "+234 855 789 0123",
      email: "info@onsema.gov.ng",
      headquarters: "Akure",
      binIdFormat: "ON######",
      billCycle: "monthly",
      averageBill: 3900,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Akure North", "Akure South", "Ondo West", "Ondo East", "Okitipupa"],
    },
    lgas: [
      "Akoko North-East",
      "Akoko North-West",
      "Akoko South-West",
      "Akoko South-East",
      "Akure North",
      "Akure South",
      "Ese Odo",
      "Idanre",
      "Ifedore",
      "Ilaje",
      "Ile Oluji/Okeigbo",
      "Irele",
      "Odigbo",
      "Okitipupa",
      "Ondo East",
      "Ondo West",
      "Ose",
      "Owo",
    ],
    population: 3460877,
    isActive: true,
  },
  osun: {
    name: "Osun",
    code: "OS",
    capital: "Osogbo",
    wasteAuthority: {
      name: "OSSEMA",
      fullName: "Osun State Environmental Management Agency",
      code: "OSSEMA",
      website: "https://osunstate.gov.ng",
      phone: "+234 857 890 1234",
      email: "info@ossema.gov.ng",
      headquarters: "Osogbo",
      binIdFormat: "OS######",
      billCycle: "monthly",
      averageBill: 3500,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Osogbo", "Ile-Ife", "Ilesa", "Ede", "Iwo"],
    },
    lgas: [
      "Atakunmosa East",
      "Atakunmosa West",
      "Aiyedaade",
      "Aiyedire",
      "Boluwaduro",
      "Boripe",
      "Ede North",
      "Ede South",
      "Egbedore",
      "Ejigbo",
      "Ife Central",
      "Ife East",
      "Ife North",
      "Ife South",
      "Ifedayo",
      "Ifelodun",
      "Ila",
      "Ilesa East",
      "Ilesa West",
      "Irepodun",
      "Irewole",
      "Isokan",
      "Iwo",
      "Obokun",
      "Odo Otin",
      "Ola Oluwa",
      "Olorunda",
      "Oriade",
      "Orolu",
      "Osogbo",
    ],
    population: 3416959,
    isActive: true,
  },
  oyo: {
    name: "Oyo",
    code: "OY",
    capital: "Ibadan",
    wasteAuthority: {
      name: "OYSEMA",
      fullName: "Oyo State Environmental Management Agency",
      code: "OYSEMA",
      website: "https://oyostate.gov.ng",
      phone: "+234 859 901 2345",
      email: "info@oysema.gov.ng",
      headquarters: "Ibadan",
      binIdFormat: "OY######",
      billCycle: "monthly",
      averageBill: 4200,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Ibadan North", "Ibadan South", "Ogbomoso", "Oyo", "Iseyin"],
    },
    lgas: [
      "Afijio",
      "Akinyele",
      "Atiba",
      "Atisbo",
      "Egbeda",
      "Ibadan North",
      "Ibadan North-East",
      "Ibadan North-West",
      "Ibadan South-East",
      "Ibadan South-West",
      "Ibarapa Central",
      "Ibarapa East",
      "Ibarapa North",
      "Ido",
      "Irepo",
      "Iseyin",
      "Itesiwaju",
      "Iwajowa",
      "Kajola",
      "Lagelu",
      "Ogbomoso North",
      "Ogbomoso South",
      "Ogo Oluwa",
      "Olorunsogo",
      "Oluyole",
      "Ona Ara",
      "Orelope",
      "Ori Ire",
      "Oyo East",
      "Oyo West",
      "Saki East",
      "Saki West",
      "Surulere",
    ],
    population: 5580894,
    isActive: true,
  },
  plateau: {
    name: "Plateau",
    code: "PL",
    capital: "Jos",
    wasteAuthority: {
      name: "PLASEMA",
      fullName: "Plateau State Environmental Management Agency",
      code: "PLASEMA",
      website: "https://plateaustate.gov.ng",
      phone: "+234 861 012 3456",
      email: "info@plasema.gov.ng",
      headquarters: "Jos",
      binIdFormat: "PL######",
      billCycle: "monthly",
      averageBill: 3800,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Jos North", "Jos South", "Jos East", "Pankshin", "Mangu"],
    },
    lgas: [
      "Barkin Ladi",
      "Bassa",
      "Jos East",
      "Jos North",
      "Jos South",
      "Kanam",
      "Kanke",
      "Langtang North",
      "Langtang South",
      "Mangu",
      "Mikang",
      "Pankshin",
      "Qua'an Pan",
      "Riyom",
      "Shendam",
      "Wase",
      "Bokkos",
    ],
    population: 3178712,
    isActive: true,
  },
  rivers: {
    name: "Rivers",
    code: "RI",
    capital: "Port Harcourt",
    wasteAuthority: {
      name: "RIWAMA",
      fullName: "Rivers State Waste Management Agency",
      code: "RIWAMA",
      website: "https://riwama.gov.ng",
      phone: "+234 84 234 5678",
      email: "info@riwama.gov.ng",
      headquarters: "Port Harcourt",
      binIdFormat: "RI######",
      billCycle: "monthly",
      averageBill: 5200,
      paymentMethods: ["card", "bank_transfer", "ussd", "mobile_money"],
      zones: ["Port Harcourt", "Obio-Akpor", "Eleme", "Ikwerre", "Oyigbo"],
    },
    lgas: [
      "Abua/Odual",
      "Ahoada East",
      "Ahoada West",
      "Akuku-Toru",
      "Andoni",
      "Asari-Toru",
      "Bonny",
      "Degema",
      "Eleme",
      "Emuoha",
      "Etche",
      "Gokana",
      "Ikwerre",
      "Khana",
      "Obio/Akpor",
      "Ogba/Egbema/Ndoni",
      "Ogu/Bolo",
      "Okrika",
      "Omuma",
      "Opobo/Nkoro",
      "Oyigbo",
      "Port Harcourt",
      "Tai",
    ],
    population: 5198716,
    isActive: true,
  },
  sokoto: {
    name: "Sokoto",
    code: "SO",
    capital: "Sokoto",
    wasteAuthority: {
      name: "SOSEMA",
      fullName: "Sokoto State Environmental Management Agency",
      code: "SOSEMA",
      website: "https://sokotostate.gov.ng",
      phone: "+234 863 123 4567",
      email: "info@sosema.gov.ng",
      headquarters: "Sokoto",
      binIdFormat: "SO######",
      billCycle: "quarterly",
      averageBill: 2800,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Sokoto North", "Sokoto South", "Tambuwal", "Gwadabawa", "Illela"],
    },
    lgas: [
      "Binji",
      "Bodinga",
      "Dange Shuni",
      "Gada",
      "Goronyo",
      "Gudu",
      "Gwadabawa",
      "Illela",
      "Isa",
      "Kebbe",
      "Kware",
      "Rabah",
      "Sabon Birni",
      "Shagari",
      "Silame",
      "Sokoto North",
      "Sokoto South",
      "Tambuwal",
      "Tangaza",
      "Tureta",
      "Wamako",
      "Wurno",
      "Yabo",
    ],
    population: 4244399,
    isActive: true,
  },
  taraba: {
    name: "Taraba",
    code: "TA",
    capital: "Jalingo",
    wasteAuthority: {
      name: "TASEMA",
      fullName: "Taraba State Environmental Management Agency",
      code: "TASEMA",
      website: "https://tarabastate.gov.ng",
      phone: "+234 865 234 5678",
      email: "info@tasema.gov.ng",
      headquarters: "Jalingo",
      binIdFormat: "TA######",
      billCycle: "quarterly",
      averageBill: 3100,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Jalingo", "Wukari", "Bali", "Gembu", "Ibi"],
    },
    lgas: [
      "Ardo Kola",
      "Bali",
      "Donga",
      "Gashaka",
      "Gassol",
      "Ibi",
      "Jalingo",
      "Karim Lamido",
      "Kumi",
      "Lau",
      "Sardauna",
      "Takum",
      "Ussa",
      "Wukari",
      "Yorro",
      "Zing",
    ],
    population: 2294800,
    isActive: true,
  },
  yobe: {
    name: "Yobe",
    code: "YO",
    capital: "Damaturu",
    wasteAuthority: {
      name: "YOSEMA",
      fullName: "Yobe State Environmental Management Agency",
      code: "YOSEMA",
      website: "https://yobestate.gov.ng",
      phone: "+234 867 345 6789",
      email: "info@yosema.gov.ng",
      headquarters: "Damaturu",
      binIdFormat: "YO######",
      billCycle: "quarterly",
      averageBill: 2600,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Damaturu", "Potiskum", "Gashua", "Nguru", "Geidam"],
    },
    lgas: [
      "Bade",
      "Bursari",
      "Damaturu",
      "Fika",
      "Fune",
      "Geidam",
      "Gujba",
      "Gulani",
      "Jakusko",
      "Karasuwa",
      "Machina",
      "Nangere",
      "Nguru",
      "Potiskum",
      "Tarmuwa",
      "Yunusari",
      "Yusufari",
    ],
    population: 2321339,
    isActive: false, // Due to security challenges
  },
  zamfara: {
    name: "Zamfara",
    code: "ZA",
    capital: "Gusau",
    wasteAuthority: {
      name: "ZASEMA",
      fullName: "Zamfara State Environmental Management Agency",
      code: "ZASEMA",
      website: "https://zamfarastate.gov.ng",
      phone: "+234 869 456 7890",
      email: "info@zasema.gov.ng",
      headquarters: "Gusau",
      binIdFormat: "ZA######",
      billCycle: "quarterly",
      averageBill: 2500,
      paymentMethods: ["card", "bank_transfer", "ussd"],
      zones: ["Gusau", "Kaura Namoda", "Talata Mafara", "Zurmi", "Anka"],
    },
    lgas: [
      "Anka",
      "Bakura",
      "Birnin Magaji/Kiyaw",
      "Bukkuyum",
      "Bungudu",
      "Gummi",
      "Gusau",
      "Kaura Namoda",
      "Maradun",
      "Maru",
      "Shinkafi",
      "Talata Mafara",
      "Chafe",
      "Zurmi",
    ],
    population: 3278873,
    isActive: false, // Due to security challenges
  },
}

export const getStateByCode = (code: string): StateData | undefined => {
  return Object.values(NIGERIAN_STATES).find((state) => state.code.toLowerCase() === code.toLowerCase())
}

export const getActiveStates = (): StateData[] => {
  return Object.values(NIGERIAN_STATES).filter((state) => state.isActive)
}

export const getStatesByRegion = () => {
  const regions = {
    "North Central": ["fct", "benue", "kogi", "kwara", "nasarawa", "niger", "plateau"],
    "North East": ["adamawa", "bauchi", "borno", "gombe", "taraba", "yobe"],
    "North West": ["jigawa", "kaduna", "kano", "katsina", "kebbi", "sokoto", "zamfara"],
    "South East": ["abia", "anambra", "ebonyi", "enugu", "imo"],
    "South South": ["akwaibom", "bayelsa", "crossriver", "delta", "edo", "rivers"],
    "South West": ["ekiti", "lagos", "ogun", "ondo", "osun", "oyo"],
  }

  return regions
}

export const searchStates = (query: string): StateData[] => {
  const lowercaseQuery = query.toLowerCase()
  return Object.values(NIGERIAN_STATES).filter(
    (state) =>
      state.name.toLowerCase().includes(lowercaseQuery) ||
      state.capital.toLowerCase().includes(lowercaseQuery) ||
      state.wasteAuthority.name.toLowerCase().includes(lowercaseQuery) ||
      state.lgas.some((lga) => lga.toLowerCase().includes(lowercaseQuery)),
  )
}
